### ISSUE TITLE
Parallel by data: nemo.data merges data from top-level keys

### ISSUE THREAD

**Issue by dwbruhn** [krakenjs/nemo#32] opened 2018-08-14 16:30 UTC
If you run nemo with parallel:data using a data source where a sub-level key is the same as one of the other top-level keys, then nemo.data merges the identical keys, even though they're on separate levels:

#### data source:
```js
{
    "A": {
        "dataset": 1,
        "B": {
            "This should be the only property A can access under B": 1
        }
    },
    "B": {
        "dataset": 2
    }
}
```

#### minimal test code:
```js
console.log("dataset:", nemo.data.dataset);
console.log(nemo.data);
```

#### output:
```
// A case
dataset: 1
{ A:
   { dataset: 1,
     B: { 'This should be the only property A can access under B': 1 } },
  B:
   { dataset: 2,
     'This should be the only property A can access under B': 1 },
  dataset: 1 }

// B case
dataset: 2

{ A:
   { dataset: 1,
     B: { 'This should be the only property A can access under B': 1 } },
  B: { dataset: 2 },
  dataset: 2 }
```

In both cases, the data from inside `A` or `B` is available at the top level of `nemo.data`, but the `A` and `B` keys are also there. Since `A` has its own `B` property, it gets merged with the top-level `B` data.

When running parallel by data, I would expect `nemo.data` to only contain the data from each top-level key at a time, namely:

```
// A case

{
  "dataset": 1,
  "B": {
    "This should be the only property A can access under B": 1
  }
}

// B case
{
  "dataset": 2
}
```

**Comment by sainianubhav** [comment] 2018-10-10 15:30
@grawk Could you let me know where to start on this issue?

**Comment by grawk** [comment] 2018-10-15 16:42
Hey @sainianubhav sorry I just saw your message here.

I'm thinking the issue must be introduced by, and may be resolved by changing, this function:
https://github.com/krakenjs/nemo/blob/master/lib/flow.js#L128-L166

**Comment by grawk** [comment] 2018-10-28 15:18
Hey @dwbruhn I tried to reproduce this. Please see the following commit:
https://github.com/krakenjs/nemo/commit/5d7ab87dd4d0455035fa50109de31798f638868f

Here is the output I got:
```
dataset: 1
dataset: 2
{ dataset: 2, baseUrl: 'https://www.google.com' }
{ dataset: 1,
  B: { 'This should be the only property A can access under B': 1 },
  baseUrl: 'https://www.google.com' }
```

 It looks like there isn't pollution from one dataset to the other in my example.

**Comment by grawk** [comment] 2018-11-01 20:04
Can't reproduce. Closing.

**Comment by dwbruhn** [comment] 2018-11-15 21:11
Hey @grawk, sorry for the delay (I was out on PTO).

The contamination only happens when the data is in the base profile. Keep your same test, but move the `data` section to the `base` profile, then you'll see it.

Here's the minimal `config.json` needed to reproduce:

```json
{
    "output": {
        "reports": "path:report"
    },
    "profiles": {
        "base": {
            "maxConcurrent": 1,
            "tests": "path:./*.js",
            "driver": {
                "browser": "chrome"
            },
            "mocha": {
                "timeout": 180000,
                "reporter": "mochawesome"
            },
            "parallel": "data",
            "data": {
                "A": {
                    "dataset": 1,
                    "B": {
                        "This should be the only property A can access under B": 1
                    }
                },
                "B": {
                    "dataset": 2
                }
            }
        }
    }
}
```

**Comment by grawk** [comment] 2018-11-17 20:06
Thanks for the additional info. I'm able to reproduce and have a fix in progress.

**Closed** 2018-12-12 17:41 UTC
Labels: help wanted
